# Generated by Django 4.2.7 on 2023-12-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='userslist',
        ),
    ]
