# Generated by Django 4.2.7 on 2023-12-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_room_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='userslist',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
